apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: custom-wasm-filter
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  url: oci://webassemblyhub.io/hiroyoshii/sample:v1.0
  imagePullPolicy: IfNotPresent
  imagePullSecret: webassemblyhub-secret
  phase: AUTHN
  pluginConfig:
    openid_server: authn
    openid_realm: ingress